name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version-file: ./pyproject.toml

      - name: Install dependencies
        run: |
          uv pip install -e . --group test --system

      - name: Run tests
        run: |
          uv run pytest tests --cov=pyproject --junitxml=junitxml.xml --cov-report "xml:coverage.xml"; exit ${PIPESTATUS[0]}

      - name: Test coverage comment
        uses: MishaKav/pytest-coverage-comment@ae0e8a539a3f310aefb3bfb6a2209778a21fa42b # v1.2.0
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./junitxml.xml
          report-only-changed-files: true
